security:
    encoders:
        Acme\UserBundle\Entity\User:
            algorithm:   sha1
            iterations: 10
            encode_as_base64: true
        Symfony\Component\Security\Core\User\User:
            algorithm:   sha1
            iterations: 10
            encode_as_base64: true

    role_hierarchy:
        ROLE_RESTAURANT_ADMIN:		ROLE_RESTAURANT_ADMIN
        ROLE_ORDER_MANAGER:			ROLE_ORDER_MANAGER
        ROLE_RESTAURANT_DIRECTOR:	[ROLE_RESTAURANT_DIRECTOR, ROLE_RESTAURANT_ADMIN, ROLE_ORDER_MANAGER]
        ROLE_ADMIN:          			[ROLE_ADMIN, ROLE_COMPANY_ADMIN, ROLE_ORDER_MANAGER, ROLE_RESTAURANT_DIRECTOR]
        ROLE_COMPANY_ADMIN:			ROLE_COMPANY_ADMIN
        ROLE_SUPER_ADMIN:			[ROLE_SUPER_ADMIN, ROLE_COMPANY_ADMIN, ROLE_ADMIN]
        

    providers:
        chain_provider:
            providers: [in_memory, user_db]
        in_memory:
            users:
                super_admin: { password: z3HXBWxM9rvJX1MijCTh7N+GbQo= , roles: 'ROLE_SUPER_ADMIN' } 
                  #1234
        user_db:
            entity: { class: AcmeUserBundle:User, property: username}

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        secured_area:
            form_login: ~
            logout: ~
            anonymous: ~
            http_basic:
                realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
