<?php

namespace Supplier\SupplierBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RestaurantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestaurantRepository extends EntityRepository
{
	public function findOneByIdJoinedToCompany($rid, $cid)
	{
		$query = $this->getEntityManager()
			->createQuery('
				SELECT r, c FROM SupplierBundle:Restaurant r
				JOIN r.company c
				WHERE r.id = :rid AND c.id = :cid'
			)->setParameters(array('rid'=> $rid, 'cid'=> $cid));

		try {
			return $query->getSingleResult();
		} catch (\Doctrine\ORM\NoResultException $e) {
			return null;
		}
	}
}
